### PR TITLE
Bugfix: Suppress COMPLEX_EXPRESSION in .gradle.kts

### LINKED ISSUE #1148: `COMPLEX_EXPRESSION` can be softened for gradle scripts
## Describe the bug
```kotlin
dependencies {
    api(projects.saveCloudCommon)
    implementation(libs.spring.cloud.starter.gateway)
}
```
causes a lot of `COMPLEX_EXPRESSIONS`, but it doesn't make sense in gradle configs.

## Environment information
* diktat version: 1.0.0

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Fixes
* Minor refactoring
* Tests

This pull request closes #1148

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt [hunk 1]
```diff
@@ -216,6 +218,14 @@ class NewlinesRule(configRules: List<RulesConfig>) : DiktatRule(
         }
     }
 
+    private fun checkForComplexExpression(node: ASTNode) {
+        if (node.getRootNode().getFilePath().isGradleScript()) {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:222]: Where this method `isGradle` comes from? Is it our extension? 
May be one day we can move this logic to Rule class, so it will skip some rules for some groups of patterns.

**Review by akuleshov7 — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/files/NewlinesRule.kt:222]: Yes, it's from one of our utils files.
