### PR TITLE
gradle-plugin: fix behavior in githubActions mode

### LINKED ISSUE #1213: gradle-plugin: problems with the new `githubActions` mode
## Expected behavior
SARIF report can be identified by `.sarif` extension

## Observed behavior
https://github.com/analysis-dev/diktat/commit/0698727bcf762ce7a765098dcf36be5cebcca6a1#diff-52618882223ec0dcf8f8568e2158fd7d1f83502da075d9658d3b5e24d92f7d0fR162
SARIF report has the same name, as the project. It makes it really hard to automatically discover these reports.

## Environment information
* diktat version: 1.0.3
* build tool (maven/gradle): gradle

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Correctly set system property
* Rename report; store reports in build directory

This pull request closes #1213

### CODE REVIEW

File: diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/DiktatJavaExecTaskBase.kt [hunk 1]
```diff
@@ -186,7 +191,7 @@ open class DiktatJavaExecTaskBase @Inject constructor(
         // githubActions should have higher priority than a custom input
         if (diktatExtension.githubActions) {
             // need to set user.home specially for ktlint, so it will be able to put a relative path URI in SARIF
-            System.setProperty("user.home", project.projectDir.toString())
+            systemProperty("user.home", project.projectDir.toString())
```
Comment (akuleshov7) [inline diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/DiktatJavaExecTaskBase.kt:194]: in maven plugin this works fine?

**Review by akuleshov7 — APPROVED** [review]

File: diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/DiktatJavaExecTaskBase.kt (hunk 1 above)
Comment (petertrr) [reply diktat-gradle-plugin/src/main/kotlin/org/cqfn/diktat/plugin/gradle/DiktatJavaExecTaskBase.kt:194]: Yes, this change doesn't affect maven plugin
