### PR TITLE
Diktat analysis test (RulesConfigYamlTest) isignored now

### LINKED ISSUE #1222: Diktat analysis test (RulesConfigYamlTest) isignored now
```
RulesConfigYamlTest 
```
is not working and not checking anything

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
* fixed tests
Closes #1222

### CODE REVIEW

File: diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/RulesConfigYamlTest.kt [hunk 1]
```diff
@@ -19,12 +19,13 @@ import kotlinx.serialization.encodeToString
...
 @Suppress("UNUSED")
-value class RulesConfigYamlTest(private val pathMap: Map<String, String> =
-        mapOf("diktat-analysis.yml" to "diKTat/diktat-rules/src/main/resources/diktat-analysis.yml",
-            "diktat-analysis-huawei.yml" to "diKTat/diktat-rules/src/main/resources/diktat-analysis-huawei.yml",
-            "parent/diktat-analysis.yml" to "diKTat/diktat-analysis.yml")) {
+class RulesConfigYamlTest {
+    private val pathMap: Map<String, String> =
+            mapOf("diktat-analysis.yml" to "diKTat/diktat-rules/src/main/resources/diktat-analysis.yml",
+                "diktat-analysis-huawei.yml" to "diKTat/diktat-rules/src/main/resources/diktat-analysis-huawei.yml",
+                "../diktat-analysis.yml" to "../diktat-analysis.yml")
```
Comment (petertrr) [inline diktat-rules/src/test/kotlin/org/cqfn/diktat/ruleset/utils/RulesConfigYamlTest.kt:27]: I don't think these values should be changed, we construct the path relative to maven's `user.dir` for the third config anyway.

**Review by petertrr — APPROVED** [review]
