### PR TITLE
KotlinParseException on string concatenation for if expression

### LINKED ISSUE #1076: `KotlinParseException` in [STRING_CONCATENATION]
## Describe the bug
```kotlin
fun foo() {
    "File is" + if (fileInfo.isExecutable) "regular" else "executable"
}
```

```
org.cqfn.diktat.ruleset.utils.KotlinParseException: Text is not valid: [""Click to mark file " + if (fileInfo.isExecutable) "regular" else "executable""
```

## Observed behavior
Diktat doesn't support concatenation of string and `if` expression

## Environment information
* diktat version: 1.0.0-rc.3

### LINKED ISSUE #1141: One more `org.cqfn.diktat.ruleset.utils.KotlinParseException: Text is not valid`
```
org.cqfn.diktat.ruleset.utils.KotlinParseException: Text is not valid: [""${window.location}/execution/$id" + if (status != null) "?status=$status" else """]
```
when trying to format
```kotlin
    private fun getHrefToExecution(id: Long, status: TestResultStatus?) =
        "${window.location}/execution/$id" + if (status != null) "?status=$status" else ""
```

Full stacktrace:
```
[ERROR] 2021-12-03 18:42:55 Internal error has occurred in rule [string-concatenation]. Please make an issue on this bug at https://github.com/cqfn/diKTat/. 
                       As a workaround you can disable these inspections in yml config: <[STRING_CONCATENATION]>.
                       Root cause of the problem is in [D:\projects\save-cloud\save-frontend\src\main\kotlin\org\cqfn\save\frontend\components\views\HistoryView.kt] file.
org.cqfn.diktat.ruleset.utils.KotlinParseException: Text is not valid: [""${window.location}/execution/$id" + if (status != null) "?status=$status" else """]
	at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode(KotlinParser.kt:75)
	at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode$default(KotlinParser.kt:75)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.fixBinaryExpressionWithConcatenation(StringConcatenationRule.kt:115)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.access$fixBinaryExpressionWithConcatenation(StringConcatenationRule.kt:31)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule$detectStringConcatenation$1.invoke(StringConcatenationRule.kt:65)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule$detectStringConcatenation$1.invoke(StringConcatenationRule.kt:61)
	at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix(Warnings.kt:260)
	at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix$default(Warnings.kt:202)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.detectStringConcatenation(StringConcatenationRule.kt:61)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.logic(StringConcatenationRule.kt:44)
...
```

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
* fixed if expression in rule
closes #1076 
closes #1141

### CODE REVIEW

File: diktat-rules/src/test/resources/test/paragraph3/string_concatenation/StringConcatenationExpected.kt [hunk 1]
```diff
@@ -32,4 +32,5 @@ val myTest21 = "${x} string"
 val myTest22 = "string${foo()}"
 val myTest23 = x.toString() + foo()
 val myTest24 = foo() + "string"
-val myTest25 = "String ${valueStr?.value}"
\ No newline at end of file
+val myTest25 = "String ${valueStr?.value}"
```
Comment (akuleshov7) [inline diktat-rules/src/test/resources/test/paragraph3/string_concatenation/StringConcatenationExpected.kt:35]: two issues contained 2 tests. Or they are the same?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/StringConcatenationRule.kt [hunk 2]
```diff
@@ -155,7 +156,8 @@ class StringConcatenationRule(configRules: List<RulesConfig>) : DiktatRule(
             val rvalueTextNew = rvalueText?.trim('"')
             return "$lvalueText$rvalueTextNew"
         } else if (binaryExpressionPsi.isRvalueCallExpression() || binaryExpressionPsi.isRvalueDotQualifiedExpression() ||
-                binaryExpressionPsi.isRvalueOperation() || binaryExpressionPsi.isRvalueSafeQualifiedExpression()) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/StringConcatenationRule.kt:158]: Do we need this branch at all? Or can it be the default behaviour (like the last branch of `if`) when right side is a general KtExpression? I don't like that we need to add so many types here, I bet it will fire once again on something else.

File: diktat-rules/src/test/resources/test/paragraph3/string_concatenation/StringConcatenationExpected.kt (hunk 1 above)
Comment (Cheshiriks) [reply diktat-rules/src/test/resources/test/paragraph3/string_concatenation/StringConcatenationExpected.kt:35]: This is one problem caused by the lack of an IfExpression check.

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/StringConcatenationRule.kt (hunk 2 above)
Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/StringConcatenationRule.kt:158]: Yes, I agree.
Fixed

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/StringConcatenationRule.kt:158]: What is the reason to leave separate branch for call expression?

Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/StringConcatenationRule.kt:158]: ReferenceExpression is always a child for the CallExpression. That's why the CallExpression requires a separate condition.
example
- foo()  [CallExpression]
- - foo [ReferenceExpression]

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/StringConcatenationRule.kt:158]: But then `isRvalueReferenceExpression()` will be false and we'll get in `.isRvalueExpression()` condition, won't we?

Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/StringConcatenationRule.kt:158]: No isRvalueReferenceExpression return true if parent or one of the children will be True

**Review by petertrr — APPROVED** [review]
