### PR TITLE
Unsigned integer literal is perhaps incorrectly marked as a MAGIC_NUMBER

### LINKED ISSUE #1224: Unsigned integer literal is perhaps incorrectly marked as a MAGIC_NUMBER
## Describe the bug

Unsigned integer literal is perhaps incorrectly marked as a `MAGIC_NUMBER`

## Expected behavior

The rules for unsigned numeric values should be the same as the signed counterparts.

## Observed behavior

Unsigned integer literal is incorrectly marked as a `MAGIC_NUMBER`

```bash
[MAGIC_NUMBER] avoid using magic numbers, instead define
constants with clear names describing what the magic number means: 0U (cannot be auto-corrected)
```

## Steps to Reproduce

Assign an unsigned integer to a variable.

```kotlin
// this raises a MAGIC_NUMBER warning
var positiveNumber = 0U

// this does not have a warning
var otherNumber = 0
```

## Environment information
* diktat version: 1.0.1
* build tool (maven/gradle): gradle
* how is diktat run (CLI, plugin, etc.): gradle plugin
* kotlin version: 1.6.10
* operating system: MacOS 12.2.1
* link to a project (if your project is public): N/A

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
* fixed ignore number in MAGIC_NUMBER rule
Closes #1224

### CODE REVIEW

**Review by petertrr — APPROVED** [review]

**Review by akuleshov7 — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/MagicNumberRule.kt [hunk 1]
```diff
@@ -108,7 +108,7 @@ class MagicNumberRule(configRules: List<RulesConfig>) : DiktatRule(
     companion object {
         const val IGNORE_TEST = true
         const val NAME_ID = "aca-magic-number"
-        val ignoreNumbersList = listOf("-1", "1", "0", "2")
+        val ignoreNumbersList = listOf("-1", "1", "0", "2", "0U", "1U", "2U", "-1L", "0L", "1L", "2L", "0UL", "1UL", "2UL")
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/MagicNumberRule.kt:111]: hope that we really compare strings in the logic

Comment (Cheshiriks) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/MagicNumberRule.kt:118]: I had to change the logic a bit

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/MagicNumberRule.kt [hunk 2]
```diff
@@ -102,13 +102,20 @@ class MagicNumberRule(configRules: List<RulesConfig>) : DiktatRule(
         /**
          * Check if string is number
          */
+        // || ((this.last().uppercase() == "L" || this.last().uppercase() == "U") && this.substring(0, this.lastIndex-1).isNumber())
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter3/MagicNumberRule.kt:105]: Probably we can finally improve our `commented_out_code` rule, to ignore leading whitespaces and make trigger on such cases 😐
